### ISSUE TITLE
I used this dependency and it throwing me this error

### ISSUE THREAD

**Issue by Subrataporwal** [AgnelSelvan/upi_payment_qrcode_generator#1]
![code-snapshot](https://user-images.githubusercontent.com/68791598/151674667-0abc5904-d51f-4245-ba80-91c1daaf17a5.png)

**Comment by AgnelSelvan** [comment]
The issue is that we need to allow the storage permission inorder to display the image

**Comment by Subrataporwal** [comment]
Any guide on how to do that?

**Comment by Subrataporwal** [comment]
Just Added This in android/app/src/main/AndroidManifest.xml
` <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
     <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>`
     
     
     
![code-snapshot](https://user-images.githubusercontent.com/68791598/152108949-262398e3-24e6-4f24-b65f-2d927efeee71.png)

**Comment by AgnelSelvan** [comment]
Can you specify the android version?
If Android Version is 10 or 10+ then you need to add this in your android/app/src/main/AndroidManifest.xml
```
<application
      android:requestLegacyExternalStorage="true"
```
