### ISSUE TITLE
How can I use this on PHP

### ISSUE THREAD

**Issue by kslakhani** [AgnelSelvan/upi_payment_qrcode_generator#13]
I want to generate qr code dynamically on my php based website.
Can somebody please describe how can I implement it?
Thanks

**Comment by AgnelSelvan** [comment]
Hello @kslakhani, you can check the UPI deep link URL (https://stackoverflow.com/a/74364961) and generate a QR Code from the UPI link. Checkout this NPCI linking PDF for more information [https://www.labnol.org/files/linking.pdf](https://www.labnol.org/files/linking.pdf)
