### ISSUE TITLE
QR code not regenerate based on onchange method

### ISSUE THREAD

**Issue by kvenkataprasad** [AgnelSelvan/upi_payment_qrcode_generator#6]
Hi, 

             I have two upi Id's GPay and PhonePe Radio group options. I want to generate QR code based on selected option. I am unable to regenerate (refreshing) QR Code with below code. It is always showing initial  UPI data (first option) only.

 onChanged: (value) {
                          setState(() {
                            selectedUPIPayment = value;
                            upiDetails = UPIDetails(
                              upiID: selectedUPIPayment!.upi!,
                              payeeName: selectedUPIPayment!.acntName!,
                              transactionID: "",
                            );
                          });
                        },

please help me.

**Comment by AgnelSelvan** [comment]
Hello @kvenkataprasad ,
Can you please share me the code if possible by hiding the required details.

Thank you.

**Comment by AgnelSelvan** [comment]
Hey @kvenkataprasad , 
Since no more details were provided closing this issue. If you find this issue to be reproducible. Please add more comments and reopen this issue.

Thank You.
