### ISSUE TITLE
UPI QR code is not working for PhonePe UPI ID by scanning in PhonePe app

### ISSUE THREAD

**Issue by venkat-pandi** [AgnelSelvan/upi_payment_qrcode_generator#9]
Hi,
I have a code, where I have given my phonepe upi id and payee name, QR code got generated, but whenever I am scanning that QR code in phonepe app, it is showing warning like 'Unable to verify QR / Invalid QR', suppose if I scan the same QR in paytm or Gpay, it is working.

Issue : PhonePe UPI ID configured, unable to scan the QR in PhonePe app itself, It's not supporting,

Can you help me on this.

**Comment by AgnelSelvan** [comment]
Hello @venkat-pandi ,
Thank you for reporting this issue.
